### PR TITLE
feat: GA cookies

### LINKED ISSUE #52: feat: Google Analytics support
Add support for Google Analytics by adding the following tag to every page of the website, immediately after the `<head>` element (the `MEASUREMENT-ID` needs to be replaced of course):

```html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=MEASUREMENT-ID"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'MEASUREMENT-ID');
</script>
```

You will need to find out how to do this in the proper Next JS way. Online resources will help, e.g., see [here](https://mariestarck.com/add-google-analytics-to-your-next-js-application-in-5-easy-steps/) and [here](https://nextjs.org/docs/messages/next-script-for-ga).

I will share the `MEASUREMENT-ID` privately, please contact me.

### PR DESCRIPTION
**Pull request by git-anurag-hub**
## Description

Fixes #52

This pull request addresses several important aspects:

- Google Analytics Support: The primary objective is to integrate Google Analytics support into our landing page. This will enable us to gather valuable insights into user behavior and engagement.

- Simplifying Consent Management: It also resolves the issue highlighted in [this discussion](https://github.com/elixir-cloud-aai/landing-page/pull/97#discussion_r1110924928) by streamlining the consent management process. Instead of relying on two additional libraries, we are now reducing unnecessary bloat in our codebase.

- Enhanced Consent Control: To manage user consents efficiently, we are leveraging [Google's Official consent support](https://developers.google.com/tag-platform/security/guides/consent#gtag.js_1). With this implementation, the Google Analytics tag will load on the initial page render, but tracking will not commence until the user explicitly clicks the "Accept" button. Additionally, if a user declines tracking, this decision will be conveyed to the Google Analytics dashboard, ensuring transparency and compliance with privacy regulations.

These improvements aim to enhance the user experience, streamline our codebase, and provide more precise control over data collection and user consents.

### CODE REVIEW

**Review by uniqueg — COMMENTED** [review]
This sounds good. Please try to resolve the CI issue.

**Comment by git-anurag-hub** [comment]
> This sounds good. Please try to resolve the CI issue.

Yeah actually OC deployment failed due to some token issue! I am not sure what it is (as I have not set it up initially) but will look into it.

**Comment by git-anurag-hub** [comment]
Hey @uniqueg, the env variable here have expired & is giving the error 403 now https://github.com/elixir-cloud-aai/landing-page/blob/dev/.github/workflows/build.yml#L53. Also I am not sure why are we deploying the app on the PR itself. Isn't the deployment will be limited to the `dev` & `master`. 

Maybe @Socuz will have more idea regarding this as he have set this up initially.

**Comment by git-anurag-hub** [comment]
Thanks for the prompt help @Socuz, I think the deployment will only be limited when the pr is merged in the dev as anyone publicly have the access to make the pr but not all have the access to push to dev (I will change it to the `push` rather than `pull_request`). For the pr deployment we are using vercel & it work completely fine.

Also can you please help me find the deployment URL?

**Comment by Socuz** [comment]
Ok, it can be improved with this: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges

I am not sure what you mean by deployment URL. Where the app is hosted?

**Comment by git-anurag-hub** [comment]
> Ok, it can be improved with this: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges
> 
> I am not sure what you mean by deployment URL. Where the app is hosted?

Yes!

**Pull request merged**
