### PR TITLE
feat: search & filter contributors

### PR DESCRIPTION
**Pull request by tanya17-05**
Added feature search and filter contributor (#15)
[Refer to this document to see changes in UI](https://docs.google.com/document/d/13EqdWZOdR92CVjZUPMlqGnol_lIhwWSGABiu0nRFacA/edit?usp=sharing)

### CODE REVIEW

**Comment by uniqueg** [comment]
I think I would just merge without any additional reviews of you manage to resolve the conflicts, @tanya17-05.

If all goes well, we will have the development environment soon. If necessary, we can then find and fix any issues easily.

**Comment by tanya17-05** [comment]
@uniqueg done 🙌

**Comment by uniqueg** [comment]
Awesome! Anurag told me he wanted to have another look tomorrow morning. So I'll wait for that :)

**Comment by git-anurag-hub** [comment]
Hey @tanya17-05, Great work. 

Just some improvements:
- The 3rd & 4th points in the [issue](https://github.com/elixir-cloud-aai/landing-page/issues/15#issuecomment-1295837286) was to have the different dropdown for both role (multiple select) & affiliation (single select) but I think you have combined them both. Can you maybe check that?
- Also the UI for different components is distinctive from the website. But I understand that the lack of UI guidelines/components can be the reason for that. (I will make the commit regarding this on this pr to solve this).
- Also the code is not properly linted/formatted. (I have made the commit for that by linting).

**Comment by tanya17-05** [comment]
Thankyou @git-anurag-hub for the linters. Regarding the first point, as per the current Notion model, roles and affiliations is one and same which is mentioned in [PR#37](https://github.com/elixir-cloud-aai/landing-page/pull/37) that's why I've merged them and considering the 2nd point, please let me know if I can contribute to the UI guidelines. 😊

**Review by uniqueg — APPROVED** [review]

**Comment by git-anurag-hub** [comment]
Thanks @tanya17-05 for changes, @uniqueg there are some changes left from my side in this pr, will merge this after committing those changes!

**Review by git-anurag-hub — APPROVED** [review]
LGTM!

**Pull request merged**
