### PR TITLE
feat: add doc links, remove guides

### PR DESCRIPTION
**Pull request by samyak-max**
Removed giudes link from navbar and added new section Docs in footer.

Screenshot (295)

### CODE REVIEW

**Review by uniqueg — CHANGES_REQUESTED** [review]
Thanks @samyak-max, looks good.

Two things though:
- The PR is based off the consent cookie branch, so all the changes from that branch are in this one, too, even though working on this feature may not have changed any of the files that were changed for the other PR. Or did it? It's hard to say and it makes reviewing very hard. Always try to create your feature branches off of `dev` and keep them in sync with `dev`. Assuming that a certain PR from another feature branch will be merged as is is dangerous, things can easily become very convoluted. You can probably cherry pick your commit for the guides/docs and add it on top of a new feature branch created from the current dev, then open another PR.
- I am not absolutely sure, but I think apart from the link in the nav bar, there is some logic in some of the files that links guides to contributors. I think that would need to be removed too. @git-anurag-hub will know more

**Review by git-anurag-hub — CHANGES_REQUESTED** [review]
Hey @samyak-max,
- Agree to Alex of the first point.
- Secondly I am not sure if I am able to see the changes in the footer of the website. This pr has been deployed [here](https://landing-page-git-remove-guides-page-elixir-cloud-aai.vercel.app/). Can you verify that you have pushed your whole code. I thin you have missed something.

@uniqueg Guides & Contributors are connected for the logic of getting the contributor for the each of the guide (as they are connected by the _id in the notiondb). It will not affect the functionality here. But if we are removing the guides entirely from of website & is linking it to the external link I will suggest that we should remove the unused logic & code for the same here.

**Comment by uniqueg** [comment]
> Hey @samyak-max,
> 
> * Agree to Alex of the first point.
> * Secondly I am not sure if I am able to see the changes in the footer of the website. This pr has been deployed [here](https://landing-page-git-remove-guides-page-elixir-cloud-aai.vercel.app/). Can you verify that you have pushed your whole code. I thin you have missed something.
> 
> @uniqueg Guides & Contributors are connected for the logic of getting the contributor for the each of the guide (as they are connected by the `_id` in the notiondb). It will not affect the functionality here. But if we are removing the guides entirely from of website & is linking it to the external link I will suggest that we should remove the unused logic & code for the same here.

Good catch with the footer, @git-anurag-hub.

And yes, as we are going to remove the guides entirely (in favor of the new Documentation Hub), I think the unused logic/code should be removed.

**Comment by samyak-max** [comment]
> Hey @samyak-max,
> 
> * Agree to Alex of the first point.
> * Secondly I am not sure if I am able to see the changes in the footer of the website. This pr has been deployed [here](https://landing-page-git-remove-guides-page-elixir-cloud-aai.vercel.app/). Can you verify that you have pushed your whole code. I think you have missed something.
> 
> @uniqueg Guides & Contributors are connected for the logic of getting the contributor for the each of the guide (as they are connected by the `_id` in the notiondb). It will not affect the functionality here. But if we are removing the guides entirely from of website & is linking it to the external link I will suggest that we should remove the unused logic & code for the same here.

Okay, I'll create a new PR based on the dev branch with the required changes. 👍

**Pull request closed without merging**
