### PR TITLE
ci: push image & deploy at CSC

### PR DESCRIPTION
**Pull request by Socuz**
Update of the GitHub Actions workflow:
- Build and Push to Docker Hub
- Deploy to OpenShift

This workflow is triggered when a pull_request on the branch dev is done.

### CODE REVIEW

**Review by uniqueg — COMMENTED** [review]
Fantastic - thanks a lot @Socuz! Can't wait to see it in action :)

Will ask @git-anurag-hub for a review as well.

**Review by uniqueg — APPROVED** [review]

**Review by uniqueg — CHANGES_REQUESTED** [review]
Just saw that the OpenShift deployment fails because it already exists. Guess it should be easy to fix

**Comment by uniqueg** [comment]
@git-anurag-hub: If this looks good to you, you can go ahead and merge. Thanks again @Socuz!

**Review by git-anurag-hub — APPROVED** [review]
Thanks @Socuz, LGTM! 
cc: @uniqueg

**Pull request merged**
