### PR TITLE
style: footer alignment in mobile view

### PR DESCRIPTION
**Pull request by psankhe28**
resolves https://github.com/elixir-cloud-aai/landing-page/issues/114

Initial:

[screen-capture-initial.webm](https://github.com/elixir-cloud-aai/landing-page/assets/84843461/0b7a5b84-e979-4752-9ea9-db0a2b09a3ac)

After:

[screen-capture-after.webm](https://github.com/elixir-cloud-aai/landing-page/assets/84843461/b62479f0-ecf2-4b78-b789-5331808397f9)

### CODE REVIEW

**Review by git-anurag-hub — CHANGES_REQUESTED** [review]
Hi @psankhe28, Great job! LGTM. One suggestion: Instead of adjusting the gap between the flex items, consider changing the horizontal padding of the flex.

**Comment by uniqueg** [comment]
Thanks a lot @psankhe28 :)

I have invited you to the relevant teams of our organization so that in the future you can create PRs from feature branches rather than from forks. In that case, you don't need to wait until we authorize the CI runs, and you can also run CI jobs that require secrets.

**Review by psankhe28 — COMMENTED** [review]
The code for adjusting the gap was already present initially, and since it was working perfectly fine, I didn't make any changes. Do you think I should modify it?

**Comment by uniqueg** [comment]
@git-anurag-hub: Can you please have a final look at this PR and, specifically, address @psankhe28's comment? :pray:

**Comment by git-anurag-hub** [comment]
> The code for adjusting the gap was already present initially, and since it was working perfectly fine, I didn't make any changes. Do you think I should modify it?

Hey @psankhe28, sure you can modify it!

**Comment by psankhe28** [comment]
> > The code for adjusting the gap was already present initially, and since it was working perfectly fine, I didn't make any changes. Do you think I should modify it?
> 
> Hey @psankhe28, sure you can modify it!

Okay, I will do the necessary changes.

**Comment by psankhe28** [comment]
@git-anurag-hub Please have a look and let me know if there is anything else that needs to be changed. Thanks!

**Review by psankhe28 — COMMENTED** [review]
I have done the changes

**Review by git-anurag-hub — APPROVED** [review]

**Pull request merged**
