### PR TITLE
fix: null data checks 

### PR DESCRIPTION
**Pull request by Chaitanya674**
Fixes : null data checks #117

- I created a null check where the utils/contributors.js and utils/solutions.js in order to send the data as an empty array [].
- because If we dont send this well have bunch of errors same as described in the issue.
- the frontend error display work on the .length parameter of array if its  0 then the UI changes to no contributors found.
- I have run a linter test as well.

### CODE REVIEW

**Review by git-anurag-hub — CHANGES_REQUESTED** [review]
Hey @Chaitanya674, Thanks for the PR! LGTM, but can you please remove the console logs from the client side. Thanks

**Comment by Chaitanya674** [comment]
yeah sure

**Review by git-anurag-hub — APPROVED** [review]

**Comment by git-anurag-hub** [comment]
Thanks @Chaitanya674 for the PR, will merge!

**Comment by Chaitanya674** [comment]
> Thanks @Chaitanya674 for the PR, will merge!

Happy to contribute : )

**Pull request merged**
