### PR TITLE
fix: Slack link expired

### PR DESCRIPTION
**Pull request by psankhe28**
Solves the issue #113

### CODE REVIEW

**Review by uniqueg — APPROVED** [review]

**Comment by uniqueg** [comment]
LGTM but we can't merge yet because of (presumably) some unrelated issue we have with the Vercel builds. See https://github.com/elixir-cloud-aai/cloud-components/issues/240

**Comment by psankhe28** [comment]
@uniqueg, I'd like to discuss the "Dashboard Web Components (React, Vue, etc.) for file upload and handling" project with you. I attempted to contact you on Slack. I understand you might be busy, but could you please let me know how I can reach you to discuss this? Alternatively, if you're unavailable, could you direct me to someone who can assist with this matter? Thank you.

**Comment by git-anurag-hub** [comment]
> @uniqueg, I'd like to discuss the "Dashboard Web Components (React, Vue, etc.) for file upload and handling" project with you. I attempted to contact you on Slack. I understand you might be busy, but could you please let me know how I can reach you to discuss this? Alternatively, if you're unavailable, could you direct me to someone who can assist with this matter? Thank you.

@psankhe28, thanks for the PR, will merge it! Please join the Slack channels and the biweekly OSS meeting on 18/03 for project-related queries.

**Comment by psankhe28** [comment]
> > @uniqueg, I'd like to discuss the "Dashboard Web Components (React, Vue, etc.) for file upload and handling" project with you. I attempted to contact you on Slack. I understand you might be busy, but could you please let me know how I can reach you to discuss this? Alternatively, if you're unavailable, could you direct me to someone who can assist with this matter? Thank you.
> 
> @psankhe28, thanks for the PR, will merge it! Please join the Slack channels and the biweekly OSS meeting on 18/03 for project-related queries.

Yes, I have joined the slack channel. I will join the biweekly OSS meeting too. Thanks!

**Pull request merged**
