### PR TITLE
Add: search and filter contributors

### PR DESCRIPTION
**Pull request by tanya17-05**
Changes are in accordance with #15 
[Refer this document to see the changes made in UI](https://docs.google.com/document/d/13EqdWZOdR92CVjZUPMlqGnol_lIhwWSGABiu0nRFacA/edit?usp=sharing) (Not able to upload screenshots here due to some error)
Note: Select role filter is not functional because roles and affiliations are merged in a single `positions array` which make it difficult to distinguish between them. Template code is written for that feature.

### CODE REVIEW

**Review by uniqueg — CHANGES_REQUESTED** [review]
Awesome 🤩 Thanks a lot @tanya17-05. And yes, I didn't think about roles and affiliations being one and the same, as per the current Notion model. I guess you could just use roles and put them all together.

Can you update accordingly? Then I'll merge.

At a later point, we could still think about separating roles from (primary) affiliations in the Notion model and readd the separate filter for the affiliations.

**Comment by git-anurag-hub** [comment]
Also @tanya17-05, it would be better if you can change the UI/UX according to the existing one:
- Use the Colors already in the use.
- Make the button border rounded & button size similar to the input field size.
- Also It would be better in UX, if you can rezise the search and maybe filter itself when you click on the filter (as there is much of the free space avaliable) & in the next line in the mobile view (I assume you have not implemented it yet).
Thanks again for the contribution. :)

**Comment by tanya17-05** [comment]
Ok @uniqueg @git-anurag-hub , I'll push these changes soon 👍

**Comment by tanya17-05** [comment]
@git-anurag-hub @uniqueg, I've made changes, please check if there is anything else to add.

**Comment by tanya17-05** [comment]
@git-anurag-hub I got the point wrong 😅. I thought you asked to make inputs to align vertically in the model itself for small devices. So basically I've to remove the modal and make the input fields to appear in the page itself, right below the search bar, when user clicks filter button (or can I just remove that button and make that filter form appear and never hiding it, what's your opinion?)

**Comment by git-anurag-hub** [comment]
I was thinking maybe we can do something like this: https://elastic.github.io/eui/#/forms/combo-box#pill-colors as this will fit our use case both on desktop & mobile. We can show all the positions, "Past contributors" & "Project leads" in the same dropdown which can then they can add up as the user clicks on them.

**Comment by git-anurag-hub** [comment]
I think the best option will be to hide the filter initially & then show it under the search field when someone clicks on it (both on desktop & mobile). 

Also, I was thinking maybe we can do something like this for Roles & Affiliation: https://elastic.github.io/eui/#/forms/combo-box#pill-colors as this will fit our use case both on desktop & mobile. We can show all the options in the same dropdown (with some sections) which can then they can add up as the user clicks on them.

Also in the requirements set by @uniqueg https://github.com/elixir-cloud-aai/landing-page/issues/15#issuecomment-1295837286, I think the 1st point was to show all the active contributors, not the past contributors. So maybe you can also see into this.

**Comment by tanya17-05** [comment]
@git-anurag-hub, got it 👍

**Comment by git-anurag-hub** [comment]
No @uniqueg there are some changes @tanya17-05 is working on it!

**Comment by git-anurag-hub** [comment]
Also @uniqueg, I think the build fails as the NOTION_TOKEN in not set in the environment which tanya pushes.

The solution for this will be to add the NOTION_TOKEN to the docker build environment rather than making it dependent on the client's environment.

**Comment by uniqueg** [comment]
@tanya17-05 did you have a chance to push this to a branch from within the organization to check if the CI pipeline passes? I would like to merge this, but would feel better with the CI checks passing

**Comment by tanya17-05** [comment]
@uniqueg I was trying to create a new branch (`filter_contributors`) and push this code from it but there is no option for me to do this. I tried to search about this issue, but I guess, I do not have access to create branch in this repository. Can you and @git-anurag-hub please suggest what I can do?

**Comment by uniqueg** [comment]
Oh, sorry, @tanya17-05, my bad. I created a new team, gave write permissions for all the front-end projects and added you (you might need to accept via email, or perhaps not, I'm not sure) and @git-anurag-hub. So I'm pretty sure with those permissions you should be able to push branches and create pull requests.

**Comment by tanya17-05** [comment]
@uniqueg no problem, just got the permissions 😊

**Comment by tanya17-05** [comment]
Since, I've made another PR by different branch. I guess this PR can be safely closed without merging.

**Pull request closed without merging**
